services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.3
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  es_data:
    name: es_data

