services:
  couchdb:
    image: couchdb:3.5.0
    container_name: couch
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secret
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - couch_alone_net

volumes:
  couchdb_data:
    name: couchdb_data

networks:
  couch_alone_net:
    name: couch_alone_net
    driver: bridge
