services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_conf:/data/configdb
      - mongo_db:/data/db

volumes:
  mongo_conf:
    name: mongo_conf
  mongo_db:
    name: mongo_db
