services:
  mongoconf:
    image: mongo
    container_name: mongo_conf
    ports:
      - "27019:27019"
    volumes:
      - config_conf:/data/configdb
      - config_db:/data/db
    networks:
      - mongo-net
    command: ["mongod", "--configsvr", "--replSet", "confSet", "--port", "27019", "--bind_ip_all"]

  mongoshard:
    image: mongo
    container_name: mongo_shard
    ports:
      - "27018:27018"
    volumes:
      - shard_db:/data/db
      - shard_conf:/data/configdb
    networks:
      - mongo-net
    command: ["mongod", "--shardsvr", "--replSet", "shardSet", "--port", "27018", "--bind_ip_all"]

volumes:
  shard_db:
  shard_conf:
  config_conf:
  config_db:

networks:
  mongo-net:
