services:
  couchdb:
    image: couchdb:latest
    container_name: deep-couch
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secret
      - COUCHDB_SECRET=dbsecret
      - NODENAME=shardx
      - ERL_FLAGS=-setcookie "brumbrum"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
    name: couchdb_data
